name: example for ghcr
on:
  registry_package:
    types: [published]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo '${{ toJSON(github.event.registry_package) }}'
          echo '${{ github.event.registry_package.package_version.container_metadata.labels.all_labels['org.opencontainers.image.source'] }}'
